### ISSUE TITLE
Странность в зеркалировании паттернов

### ISSUE THREAD

**Issue by zerotool** [noff/snek#103]
Бой https://snek.app/battles/4493 Round 121-122 Undefined должен был пойти вниз, но пошёл наверх, полный набор правил Undefined отправлен на sam@mkechinov.ru

**Comment by noff** [comment]
А ты менял с тех пор программу змеи?

**Comment by noff** [comment]
Все, я выяснил проблему. Обрати внимание: твоя змея ходит второй. На 121 ходе она должна была повернуть вниз (сработал бы первый паттерн), если бы в этот момент первая змея не ушла дальше и не утянула хвост. И в момент, когда должна была ходить твоя змея, картина на поле была уже такая:

![image](https://user-images.githubusercontent.com/937186/41502690-965ad93e-71c8-11e8-98ab-2e9779dc4078.png)

**Comment by zerotool** [comment]
Правила с того момента больше не менял

**Comment by zerotool** [comment]
Должен был сработать не первый, а вот этот, третий паттерн: 
<img width="196" alt="screen shot 2018-06-17 at 10 59 13" src="https://user-images.githubusercontent.com/1117405/41506847-7eeb0e36-721d-11e8-931b-3487a5ef67cc.png">

Ожидаемая последовательность действий:
- Синяя змея двигается вправо, её хвост тоже
- Моя змея пытается применить первый паттерн, (он не подходит по описанной тобой причине)
- Пытается применить второй - он очевиндо тоже не подходит
- При попытке применить третий, он должен отражаться горизонтально и хвост синей попадает в отражённую часть (но этого не происходит).

**Comment by noff** [comment]
Все, нашел. Зеркалирование не срабатывало все же.

**Comment by zerotool** [comment]
Ураа, теперь работает?

**Comment by noff** [comment]
Поидее да, я вручную проверил - твоя ходит на юг в этой ситуации. Помониторь еще.

**Comment by zerotool** [comment]
Что-то теперь всё сломалось, https://snek.app/battles/4525 Round 190-191 синяя змея уткнулась в тупик (а по правилу 8 должна была уйти вправо):

Ход 190:
<img width="617" alt="screen shot 2018-06-18 at 12 48 23" src="https://user-images.githubusercontent.com/1117405/41534365-3f5e9416-72f6-11e8-9973-7c2602b3fc00.png">

Ход 191
<img width="667" alt="screen shot 2018-06-18 at 12 48 34" src="https://user-images.githubusercontent.com/1117405/41534366-3f77316a-72f6-11e8-8805-de3260dab4b5.png">

Правило 8:
<img width="369" alt="screen shot 2018-06-18 at 12 50 36" src="https://user-images.githubusercontent.com/1117405/41534367-3f9086ec-72f6-11e8-90e5-f07ab9aa13e2.png">

**Comment by zerotool** [comment]
Правило 8 применяю в голове так: 
![screen-shot-2018-06-18-at-12 48 23](https://user-images.githubusercontent.com/1117405/41534498-ab0d5c6a-72f6-11e8-98b3-60f57421359a.jpg)

**Comment by zerotool** [comment]
Ни один из предыдущих семи паттернов в этой ситуации не применим вроде, отправил на почту все 9

**Comment by noff** [comment]
Похоже sidekiq не перезагрузился. Сейчас перезагружу.
А вообще у тебя должен сработать паттерн №5, отзеркаленный по горизонтали и повернутый направо.

**Comment by noff** [comment]
Перезагрузил сайдкик, попробуй еще

**Comment by zerotool** [comment]
Да, пятый тоже подходит, но не для движения вперёд, а опять же направо

**Comment by zerotool** [comment]
Да, вроде всё теперь работает. Спасибо!

**Comment by zerotool** [comment]
Блин, всё равно чего-то не хочет идти как надо: https://snek.app/battles/4530 Round 691-692 Надо было налево (по паттерну 3), пошла направо
<img width="361" alt="screen shot 2018-06-18 at 13 36 12" src="https://user-images.githubusercontent.com/1117405/41536124-993d4ab2-72fc-11e8-9d1d-d40ad218dac1.png">

**Comment by zerotool** [comment]
Ещё кейс: https://snek.app/battles/4532 R102-103 Синяя не должна была идти влево (прямо - по тому же 3му паттерну)

**Comment by zerotool** [comment]
Тот же https://snek.app/battles/4532 R174-175 безумный ход синей змеи, должен был тоже третий паттерн применяться

**Comment by noff** [comment]
Блин, глупость сморозил. Строки местами перепутал. Передеплоился.

**Comment by zerotool** [comment]
Сейчас протестим, спасибо

**Comment by zerotool** [comment]
Работает! Можно писать новость, что теперь змейки бегают чётко по правилам 👍
