### ISSUE TITLE
Странность в интерпретации правила

### ISSUE THREAD

**Issue by zerotool** [noff/snek#110]
Бой https://snek.app/battles/5714 ход 69-70. Zerro идёт влево вместо поедания хвоста Python. Первые два правила отправил на почту, должно было сработать второе:
![screen-shot-2018-06-27-at-18 13 45](https://user-images.githubusercontent.com/1117405/41989435-3589acd0-7a37-11e8-9c79-32d1db9a30af.jpg)

**Comment by zerotool** [comment]
Ещё один случай: https://snek.app/battles/5775 R554-555

**Comment by noff** [comment]
Стас, после этого менял правила?

**Comment by noff** [comment]
Тогда я задачу пока прикрою до следующего подозрительного случая.
