### ISSUE TITLE
Между запуском сохранённых бвтлов нужно обновлять страницу.

### ISSUE THREAD

**Issue by ProudHamstet** [noff/snek#126]
Телефон Xiaomi mi 5s. Странности наблюдаются при использовании как мобильного интернета так wi-fi. Ссылку на бои прикладывать бессмысленно т.к. при переходе по ним все отображается и работает нормально. Суть проблемы заключается в том, что необходимо обновлять страницу между сохраненнами батлами, иначе возникают странности в отображении, что приведено ниже. Плюс к тому на первых двух скриншотах показано, что поставить бои на паузу не представляется возможным и он продолжает идти. Меняется лишь ззначок.

![screenshot_2018-07-21-11-54-15-349_com android chrome](https://user-images.githubusercontent.com/41504832/43034044-4f6bf03c-8cdd-11e8-9501-5c4a58ce2a5c.png)
![screenshot_2018-07-21-11-54-19-535_com android chrome](https://user-images.githubusercontent.com/41504832/43034045-4f9ac3bc-8cdd-11e8-9349-e9d10f54734a.png)
![screenshot_2018-07-21-11-53-56-339_com android chrome](https://user-images.githubusercontent.com/41504832/43034046-4fcc3b9a-8cdd-11e8-90ab-4e34a939709d.png)
![screenshot_2018-07-21-11-46-39-287_com android chrome](https://user-images.githubusercontent.com/41504832/43034047-4ffe8b7c-8cdd-11e8-9fcd-4821278bd8f1.png)

**Comment by noff** [comment]
Есть ли возможность включить режим разработчика и посмотреть, что пишет в консоли?
Вот по этой инструкции: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/?hl=en

**Comment by ProudHamstet** [comment]
![zq9oudigu7s](https://user-images.githubusercontent.com/41504832/43035315-0dde0f06-8cf6-11e8-8068-bd7b8ed4b28d.jpg)

**Comment by noff** [comment]
А можете еще в консоли выполнить команду 
```gon```
?
И приложить ее сюда.
А если выполнится, то еще:
```gon.sneks```

**Comment by ProudHamstet** [comment]
Запускал два раза. Сначала используя одну, потом две команды.
![gw0vdtgkiwe](https://user-images.githubusercontent.com/41504832/43036955-d54d68e2-8d10-11e8-9885-342604a479be.jpg)
![spp2mdfygzq](https://user-images.githubusercontent.com/41504832/43036963-dbde845c-8d10-11e8-93fb-715bb3ef1848.jpg)

**Comment by noff** [comment]
Выпилил turbolinks из рельсов. 
Сейчас повторяется такая проблема?

**Comment by ProudHamstet** [comment]
Нет, все работает нормально
