### ISSUE TITLE
Накликивание корон

### ISSUE THREAD

**Issue by ProudHamstet** [noff/snek#128]
На данный момент я могу сражаться с одной и той же змеёй в топе бесконечно, бесконечно получая короны и "халявные" очки, что приятно но как то неправильно. Если бы после победы я не мог сражаться с той же змеёй, пока она, допустим, не поменяет какой-нибудь паттерн это было бы честнее и заставляло нас развиваться выдумывая для конкретной змеи конкретную стратегию, а не просто издеваясь над относительно слабой змеёй.
https://snek.app/battles/19239
https://snek.app/battles/19244

**Comment by ProudHamstet** [comment]
И касательно королевской битвы - сейчас в ней может победить любая змея а не только умные змеи, что смогли завоевать карону. Если королевская битва действительно коорлеваска, а не просто битва где куча змей, то разумно если корона будет давать не право запустить её, а право поучаствовать а ней. Когда набирается необходимое количество змей, заплативших за участие короной, вот только тогда она запускается. Конечно таких битв станет меньше, но они станут красочнее и честнее.

**Comment by ABCpt** [comment]
Тоже посещали подобные мысли. Думаю до того как появится возможность тестировать змею на сохраненных битвах урезание возможности сражаться с выбранной змеёй будет скорее вредно, чем полезно. Я, к примеру, часто использую знакомых змей с предсказуемым поведением для настройки паттернов, потому что других вариантов просто нет.

**Comment by noff** [comment]
Скорее всего потом отключу начисление корон за дуэли. Тут нужно играться с игровой механикой. Например, за победу в дуэли давать доступ в битву четырех. За победу в битве четырех выдавать корону на королевскую битву. Еще не придумал, как это сделать правильно.

По поводу брать корону с каждого участника битвы - пассивные участники (которые рандомом выбираются на битву) будут не рады, если с них начнут списываться короны. Тут тоже нужно подумать. Эту идею запомнил. Появятся еще - скидывайте в эту цепочку.

**Comment by noff** [comment]
Тогда людям станет скучно - ждать, когда начнется битва, тем более, что сейчас народу от США до Австралии по длинной стороне.
В ручном режим будут турниры - там будут денежные призы и участие только по явному желанию участника.

**Comment by ProudHamstet** [comment]
Думаю что давать доступ к битве четырех после победы в дуэли не совсем правильно. Лично для меня это совсем разные подходы к игре. В дуэли я должен создавать что - то конкретное для каждой змеи (иначе буду просто гоняться за ее хвостом как и она за моим если она хоть немного смышлёная), в битве четырех нужно делать что-то универсальное. Если королеваская это битва 4 на максималках, то может стоит создать что то и для дуэли. Например турнир где ты подаешь заявку и тебе подбирают соперника который также ее подал (заплатив чемто что будут давать уже только за победу в дуэли или дуэлях). Бой начинается не сразу, а через час например (да и турнир наверное должен начинаться когда нужное количество заявок будет подано). И у тебя есть время посмотреть последний бой данной змеи или даже паттерны которые были там использованы (не которые стоят сейчас). Сделать там четверть финалы, полуфиналы и тд и грандиозный финал где возможно тоже можно будет делать ставки.

**Comment by noff** [comment]
Логично.

**Comment by ProudHamstet** [comment]
Полагаю что победить 4 разных соперников в дуэли также сложно как победить в "битве четырех" поэтому за 4 победы можно давать ту же самую корону ничего нового не выдумывая. Если система ставок все же будет внедрена то и ставить можно будет эти самые короны. Часть поставленных корон отходит победителю. Короны можно будет покупать (например для участия в турнире) и возвращать деньги обратно за короны. Только сделать так чтобы минимальная количество ввода-возврата корон равнялась 1000

**Comment by ProudHamstet** [comment]
Насчёт того что нельзя вызывать на бой змей без режима автоматического участия в боях мне кажется неправильным. То что они не участвуют в битвах где ведётся рандомный поиск это отлично, но право подраться со змеями из топа должно быть у всех, ведь это несколько другое. До первой победы, но это я уже описывал выше.

**Comment by noff** [comment]
Если змея не в режиме автобоя, то она в режиме черновика - автор ее обучает в данный момент и не готов к боям. Поэтому он не участвует ни в пассивном режиме ни сам не может запустить бой с этой змеей.

**Comment by ProudHamstet** [comment]
Это система требует переосмысления как по мне. Вешать фложок в то время когда человек меняет паттерны дело доброе, но смотреть как змея действует можно только в боях, соответственно и флажок должен убираться как только человек выходит из настройки змеи. Да и странная это система, ведь сейчас никто ничего не теряет за проигрыши. Даже наоборот как топ 1 помог добраться UUUUUUU до десятого места, так и я помог господину HyperMauZ скакнуть с 100 до 20 кого-то места.

**Comment by noff** [comment]
Это при текущей системе оценок. Я буду ее переделывать и в ней будут участвовать такие показатели, как:
1. Количество "тупых" ходов в случайном направлении, когда ни один паттерн не сработал.
2. Соотношение числа боев к набранным баллам.
3. Количество проигрышей к количеству боев.
И т.д. В итоге получится, что змей не готов к бою, а очки теряет.
И тут же про новичков - они еще даже с правилами разобраться не успели и ни одного паттерна не сделали, а их уже задраконили. 
Как в этом случае быть?

**Comment by ProudHamstet** [comment]
Включать в формулу соотношение боёв к очкам или победам неправильно, как по мне. У меня ушло боёв 300 прежде чем я понял что к чему и тогда чтобы попасть в топ мне придется создавать новую змею? Найдутся те кто так и поступят чтобы чтобы улучшить стату. И такая система убивает желание эксеременировть чтобы не портить стату увеличивая количество неудачных игр. Новиички в топе сто? Значит уже не навички и пусть отстаивают свое место в топе. Насчёт автобоев все сейчас норм как по мне. Не хочешь не участвуешь и не выбираешься на рандоме, но ведь вызвать змею из топа это другое

**Comment by ProudHamstet** [comment]
Первый пункт я плохо понял как будет использоваться в формуле, но для отладки змеи знать в какой момент использовался какой паттерн будет отлично. Если впихнуть это в сохраненные бои будет очень удобно.

**Comment by ABCpt** [comment]
"Умную" змею в сухую победить почти нереально, поэтому получение корон превратилось в лупление змей-пинат, у которых score ~= число боёв. Чтобы уйти от принципа "избиения младенцев" можно попробовать реализовать такую схему: даем корону за любую победу(победа = перевес по очкам), но только в режиме игры с рандомным игроком; соответственно в игре по кнопке "Revenge!!" коронок не даем, используем это режим чтобы тестировать паттерны на конкретных змеях; стоимость игры в клетке с 4 змеями стоит 4 короны, в клетке с 9 змеями - девять корон; ну и можно подумать какие-то призы(те же короны) для первой тройке королевской битвы, чтобы поднять мотивацию.

**Comment by ProudHamstet** [comment]
Вообще победа = перевес по очкам вещь необходимая в битве четырех (при нынешних обстоятельствах). Сейчас выйграть там в сухую это чисто дело везения.

**Comment by noff** [comment]
Так, ребятки. Чтобы пока не спорить, я убрал Revenge. Далее я переделаю его так, чтобы месть можно было делать только той змее, которая тебя полностью съела в последнем бою. И только один раз. Так будет логичнее. Задача #132

**Comment by ProudHamstet** [comment]
Revenge убрали, и теперь подбор соперников должен быть рандомен. Эти три Батла конечно возможны, но вероятность должна быть крайне мала. Но они есть. https://snek.app/battles/24696
https://snek.app/battles/24695
https://snek.app/battles/24694

**Comment by noff** [comment]
Стас, рассказывай, как сделал.

**Comment by zerotool** [comment]
`while :; do clear; curl 'https://snek.app/battles?mode=1&opponent_id=26&snek_id=48' ........ [some boring curl data]; sleep 20; done`

Всё, что без серверной валидации и не за капчей можно (и нужно) автоматизировать.

**Comment by zerotool** [comment]
У кого-то подгорело я смотрю :)
