### ISSUE TITLE
Новые батлы не рассчитываются и даже не отображаются в батлах

### ISSUE THREAD

**Issue by ProudHamstet** [noff/snek#129]
Скриншот сделан после обновления счётчика и попытки начать новые батлы. 
![screenshot_2018-07-22-20-44-59-783_com android chrome](https://user-images.githubusercontent.com/41504832/43048446-464f8c7a-8df0-11e8-871f-2591f7b83e7c.png)
Также прикладываю ссылки на те самые батлы, что не рассчитываются. Зайти на них я смог через историю браузера 
https://snek.app/battles/19354
https://snek.app/battles/19353
https://snek.app/battles/19351
https://snek.app/battles/19347
https://snek.app/battles/19346
https://snek.app/battles/19344

И с 32 по 56 батлы тоже не рассчитываются. Не знаю к чему последняя информация.

**Comment by noff** [comment]
Это был баг с подгрузкой JS. Я поправил.

**Comment by noff** [comment]
Ссылки работают сейчас.
