### ISSUE TITLE
Неприкосаемые змеи

### ISSUE THREAD

**Issue by ProudHamstet** [noff/snek#131]
В топе есть змеи которых я не могу пригласить на дуэль.
![screenshot_2018-07-25-05-57-45-419_com android chrome](https://user-images.githubusercontent.com/41504832/43177206-be014fde-8fcf-11e8-8c20-79872e13b897.png)
![screenshot_2018-07-25-05-57-50-560_com android chrome](https://user-images.githubusercontent.com/41504832/43177207-be3b2f06-8fcf-11e8-995b-501fe2cd9361.png)
![screenshot_2018-07-25-05-57-28-738_com android chrome](https://user-images.githubusercontent.com/41504832/43177209-bf098900-8fcf-11e8-9a88-bdc984f98b3d.png)
![screenshot_2018-07-25-05-57-36-901_com android chrome](https://user-images.githubusercontent.com/41504832/43177211-bf75d27c-8fcf-11e8-8838-d40853e2e460.png)

**Comment by noff** [comment]
Змеи без кнопок - это те, у которых выключен режим автоматического принятия участия в боях.
