### ISSUE TITLE
Кнопка "добавить в избранное" в мобильной верстке

### ISSUE THREAD

**Issue by Potapych** [noff/snek#141]
Привет, а можно ли куда нибудь сдвинуть сабж на экране боя? При пошаговой отладке постоянно случайно тыкаешь в неё, в итоге бой надо прогонять заново, что ещё пол беды. Если же один раз уже случайно попал по ней, то на второй раз, экран боя закрывается и выпадает ошибка.
PS ошибка вроде больше не выпадает, но все равно покидаешь бой.
По возможности сдвиньте ее максимально далеко от элементов управления, не так часто она требуется, с учётом того, что бои сохраняются и так.

**Comment by Potapych** [comment]
А что то не особо то поменялось. Не знаю как тут скрин в мобильной версии вложить, но как то так
https://yadi.sk/i/SmXlL3KY3ZnixQ
Проверил в хроме и Яндекс браузере

**Comment by noff** [comment]
CI сломался, задеплоил руками. Теперь должно быть.

**Comment by Potapych** [comment]
А, понял, не ту кнопку убрали, извиняюсь, возможно криво сформулировал

**Comment by Potapych** [comment]
Во, супер. Только первая была полезна

**Comment by Potapych** [comment]
Отлично! Благодарю! А то доставать уже отладка начала :)
