### ISSUE TITLE
Design top navigation

### ISSUE THREAD

**Issue by noff** [noff/snek#4]
Customize twitter bootstrap CSS.
And prepare logo for the navigation bar.

**Comment by Ziilexia** [comment]
Такая идея
Странная ширина сайта 1110px
Правила немного ужал по ширине, так удобнее читать.

![main](https://user-images.githubusercontent.com/39259391/40303226-9b54c7f2-5cfa-11e8-8189-ff4bb253415c.png)
![rules](https://user-images.githubusercontent.com/39259391/40303228-9b748c9a-5cfa-11e8-85e1-7d587ff747bb.png)

**Comment by noff** [comment]
Приложи логотип сюда, чтобы я его воткнул в меню.
Меню пока не хочется дизайнить - я взял из бутстрапа.

**Comment by Ziilexia** [comment]
В архиве два лого, для светлой (как в дизайне) и для темной (как сейчас) шапки. Если будет темная то цвет такой бы сделать 0F3631
[Archive.zip](https://github.com/noff/snek/files/2022489/Archive.zip)
