### ISSUE TITLE
Ограничить запуск одновременно не более 10 боёв

### ISSUE THREAD

**Issue by zerotool** [noff/snek#53]
Ограничить запуск одновременно не более 10 боёв (появились спамеры)

**Comment by zerotool** [comment]
Имеется в виду на каждого юзера, а не всего 10 :)

**Comment by 2xG** [comment]
Ну я чутка поспамил =)
Думаю 10 на самом деле много, пары-тройки достаточно. Но к этому хорошо бы прокачать воркеров, которые битвы просчитывают.
