### ISSUE TITLE
Змея двигается не по правилам

### ISSUE THREAD

**Issue by zerotool** [noff/snek#78]
https://snek.app/battles/3424
Ситуация: 
Round 385-386, Zerro двигается к стенке, хотя ни одно из правил делать такого не советует. Кроме того, есть 9ое правило: 
<img width="352" alt="screen shot 2018-06-06 at 13 07 17" src="https://user-images.githubusercontent.com/1117405/41037234-906a8254-698a-11e8-80c4-66e7107197ac.png">
По которому Zerro должен был пойти вниз:
![screen-shot-2018-06-06-at-13 08 45](https://user-images.githubusercontent.com/1117405/41037392-1dd7dea2-698b-11e8-8b0b-68e840b9fc3c.jpg)

**Comment by zerotool** [comment]
![a](https://user-images.githubusercontent.com/1117405/41037547-884fc722-698b-11e8-8ee7-6d5293956e1f.jpg)
Я применяю в голове 9ое правило так, возможно я не прав?

**Comment by zerotool** [comment]
Я не меняю правила своей змеи больше с этого момента, чтобы можно было повторить это (если это баг)

**Comment by noff** [comment]
А у тебя нет шанса, что другие какое-то из предыдуших правил сработало?

**Comment by noff** [comment]
Потому что твоя змея ходит второй, первой ходит голубая змея, а значит твоя анализирует арену с уже походившей голубой змеей.

**Comment by noff** [comment]
```=== /Pattern Matrix ===
get_next_move: Rotate matrix #8 to E. Flip: false
=== Rotated matrix ===
default	and	default	and	default	and	default	and	default	and	default	and	default	and
default	and	default	and	default	and	default	and	default	and	default	and	default	and
default	and	default	and	default	and	default	and	default	and	default	and	default	and
default	and	default	and	default	and	my_head	and	default	and	empty	and	empty	or
default	and	default	and	default	and	default	and	empty	or	default	and	default	and
default	and	default	and	default	and	default	and	default	and	default	and	default	and
default	and	default	and	default	and	default	and	default	and	default	and	default	and
=== /Rotated matrix ===
=== Observable area ===
wall	wall	empty	body-13	body-13	empty	empty
wall	wall	empty	body-13	body-13	empty	empty
wall	wall	empty	body-13	body-13	empty	empty
wall	wall	empty	head-13	body-13	empty	empty
wall	wall	empty	empty	body-13	body-13	body-13
wall	wall	empty	empty	empty	empty	empty
wall	wall	wall	wall	wall	wall	wall
=== /Observable area ===
get_next_move: check cell (3, 3). Cell: ["head", "13"]. Pattern cell: ["my_head", "and"]
get_next_move: check cell (5, 3). Cell: empty. Pattern cell: ["empty", "and"]
get_next_move: check cell (6, 3). Cell: empty. Pattern cell: ["empty", "or"]
get_next_move: check cell (4, 4). Cell: ["body", "13"]. Pattern cell: ["empty", "or"]
get_next_move: Pattern #8 to direction E. Optional cells: {"empty"=>true}
get_next_move: Matched pattern #8 of snek 13 to direction E
```

Это дебаг.
Копаю дальше.

**Comment by zerotool** [comment]
Отправил на sam@mkechinov.ru скрин моих правил, не вижу ни одного применимого в этом кейсе, кроме 9го

**Comment by zerotool** [comment]
Даже если голубая ходит первой, она вне поля видмости моей змеи

**Comment by noff** [comment]
Почему оно ходит в E - понятно. Порядок вращения паттерна при направлении головы на юг:
`S W E`
Дальше array.pop вытаскивает последнее направление (E) и твой паттерн с ним срабатывает. Поэтому пытается пойти на E. Но там твое тело, поэтому вместо E идет в любом рандомном направлении. В этом бою на W.

**Comment by noff** [comment]
Я поменяю pop на shift, так змеи чаще будут бегать прямо.

**Comment by zerotool** [comment]
Получается, перед носом змеи надо поставить пустой квадрат, чтобы исправить это

**Comment by zerotool** [comment]
<img width="352" alt="screen shot 2018-06-06 at 13 41 22" src="https://user-images.githubusercontent.com/1117405/41038797-54d65da8-698f-11e8-922a-d0f445ea9bf9.png">
 Типа такого

**Comment by noff** [comment]
Ага.

**Comment by zerotool** [comment]
Офигеть, я думал всегда почему-то, что движение вперёд предполагает пустой квадрат перед носом автоматически, т.е. его необязательно там ставить. Это весьма неочевидно
