### ISSUE TITLE
A lot of images for Indie Go Go

### ISSUE THREAD

**Issue by noff** [noff/snek#92]
> Add more images related to your campaign. These will show up in the 'Gallery' tab of your campaign page.

5 images: rules editor, battle image, ratings, etc.

**Comment by Ziilexia** [comment]
Залил следующие скрины (в описании к обложке которая отображается в том же слайдере что и скрины стоит размер 695x460, но скрины с этим размером выглядят мыльно, поэтому залил покрупнее и максимально ужал их)
![screen 1](https://user-images.githubusercontent.com/39259391/41528041-a26ab350-72f1-11e8-8d15-dc06bf9094c4.png)
![screen 2](https://user-images.githubusercontent.com/39259391/41528042-a28d65f8-72f1-11e8-9fda-3c13f59e58f8.png)
![screen 3](https://user-images.githubusercontent.com/39259391/41528043-a2af8e58-72f1-11e8-8f7e-9c0be4c81b39.png)
![screen 4](https://user-images.githubusercontent.com/39259391/41528044-a2cc19ce-72f1-11e8-9eb9-0447be52a13a.png)
![screen 5](https://user-images.githubusercontent.com/39259391/41528045-a2ed044a-72f1-11e8-8cd0-412a6b538d08.png)
![screen 6](https://user-images.githubusercontent.com/39259391/41528047-a3294022-72f1-11e8-80f9-0295401f2660.png)
