### ISSUE TITLE
Pictures for perks

### ISSUE THREAD

**Issue by noff** [noff/snek#95]
Go to perks panel and upload perk image for each perk.

**Comment by Ziilexia** [comment]
Залил следующие картинки
![almost-co-founder](https://user-images.githubusercontent.com/39259391/41527632-6ffc0d5c-72f0-11e8-9973-dc9dff5c4441.png)
![battle-royaler](https://user-images.githubusercontent.com/39259391/41527633-70281636-72f0-11e8-9e21-ea0dbc5aaead.png)
![iddqd](https://user-images.githubusercontent.com/39259391/41527634-704628a6-72f0-11e8-9db4-1e37d195f5e6.png)
![pro-sneker](https://user-images.githubusercontent.com/39259391/41527635-70648e22-72f0-11e8-8258-15108fc50d1b.png)
![snek-dude](https://user-images.githubusercontent.com/39259391/41527636-7084eb18-72f0-11e8-88fd-3db55036f781.png)
![snek-lord](https://user-images.githubusercontent.com/39259391/41527637-70a42db6-72f0-11e8-9f83-58e66838d5b0.png)
![snek-master](https://user-images.githubusercontent.com/39259391/41527638-70c10c4c-72f0-11e8-82cc-c473c5c0445b.png)
![zookeeper](https://user-images.githubusercontent.com/39259391/41527640-70f29e9c-72f0-11e8-82fa-d1c8f9dab5f1.png)
